"""
Weekly Report Generator
Auto-generates "Cenoa Weekly Intelligence" from HYDRA data.
Outputs markdown that can be emailed, posted to blog, or sent via Telegram.
"""

from datetime import datetime, timezone
from typing import Dict, Optional
from loguru import logger


class WeeklyReportGenerator:
    """Generate weekly market intelligence report from accumulated data."""
    
    def generate(self, market_data: Dict, signal_stats: Dict = None) -> str:
        """Generate full weekly report as markdown."""
        now = datetime.now(timezone.utc)
        m = market_data
        
        report = []
        report.append(f"# Cenoa Weekly Intelligence")
        report.append(f"**Week of {now.strftime('%B %d, %Y')}**\n")
        
        # TL;DR
        report.append("## TL;DR\n")
        tldr = self._generate_tldr(m)
        report.append(tldr + "\n")
        
        # Market Overview
        report.append("## Market Overview\n")
        report.append(self._market_overview(m) + "\n")
        
        # USD Yield Benchmark
        report.append("## USD Yield Benchmark\n")
        report.append(self._usd_benchmark(m) + "\n")
        
        # ETH Staking Benchmark
        report.append("## ETH Staking Benchmark\n")
        report.append(self._eth_benchmark(m) + "\n")
        
        # DeFi vs TradFi
        report.append("## DeFi vs TradFi\n")
        report.append(self._defi_vs_tradfi(m) + "\n")
        
        # Top Opportunities
        report.append("## Top Yield Opportunities\n")
        report.append(self._top_opportunities(m) + "\n")
        
        # Capital Flows
        report.append("## Capital Flows\n")
        report.append(self._capital_flows(m) + "\n")
        
        # EM Currency Watch
        report.append("## EM Currency Watch\n")
        report.append(self._em_currencies(m) + "\n")
        
        # What to Watch
        report.append("## What to Watch Next Week\n")
        report.append(self._what_to_watch(m) + "\n")
        
        # Footer
        report.append("---")
        report.append("*Generated by Cenoa Insights · Powered by HYDRA Engine*")
        report.append(f"*{now.strftime('%Y-%m-%d %H:%M UTC')}*\n")
        
        return "\n".join(report)
    
    def _generate_tldr(self, m: Dict) -> str:
        parts = []
        
        usd_bench = m.get('usd_benchmark_apy', 0)
        eth_bench = m.get('eth_benchmark_apy', 0)
        fg = m.get('fear_greed_value', 50)
        btc = m.get('last_price', m.get('close', 0))
        t3m = m.get('treasury_3m', 0)
        
        if usd_bench:
            parts.append(f"- **USD Benchmark APY:** {usd_bench:.2f}%")
        if eth_bench:
            parts.append(f"- **ETH Benchmark APY:** {eth_bench:.2f}%")
        if t3m:
            parts.append(f"- **US 3M T-Bill:** {t3m:.2f}%")
        if btc:
            parts.append(f"- **BTC:** ${btc:,.0f}")
        if fg:
            label = self._fg_label(fg)
            parts.append(f"- **Sentiment:** {fg}/100 ({label})")
        
        etf = m.get('etf_net_flow_7d', 0)
        if etf:
            parts.append(f"- **BTC ETF 7D Flow:** ${etf/1e6:+,.0f}M")
        
        return "\n".join(parts) if parts else "Data still accumulating..."
    
    def _market_overview(self, m: Dict) -> str:
        btc = m.get('last_price', m.get('close', 0))
        chg = m.get('price_change_24h', 0)
        fg = m.get('fear_greed_value', 50)
        fgl = self._fg_label(fg)
        dom = m.get('btc_dominance', 0)
        vix = m.get('vix_current', 0)
        mcap_chg = m.get('total_mcap_change_24h', 0)
        
        lines = []
        if btc:
            lines.append(f"Bitcoin is trading at **${btc:,.0f}** ({chg:+.1f}% 24h).")
        if fg:
            if fg <= 25:
                lines.append(f"Market sentiment is at **{fg} ({fgl})** — investors are deeply fearful. Historically, extreme fear has often preceded recovery periods, but timing remains uncertain.")
            elif fg >= 75:
                lines.append(f"Market sentiment is at **{fg} ({fgl})** — euphoria is high. Exercise caution as extreme greed can precede corrections.")
            else:
                lines.append(f"Market sentiment: **{fg} ({fgl})**.")
        if dom:
            lines.append(f"Bitcoin dominance: **{dom:.1f}%**" + (" — capital concentrating in BTC." if dom > 58 else "."))
        if vix:
            lines.append(f"VIX (volatility index): **{vix:.0f}**" + (" — elevated, risk-off environment." if vix > 25 else "."))
        
        return " ".join(lines)
    
    def _usd_benchmark(self, m: Dict) -> str:
        bench = m.get('usd_benchmark_apy', 0)
        bench_30d = m.get('usd_benchmark_apy_30d', 0)
        tvl = m.get('usd_benchmark_tvl_b', 0)
        
        lines = []
        if bench:
            lines.append(f"**Cenoa USD Benchmark: {bench:.2f}% APY** (30D avg: {bench_30d:.2f}%)")
            if tvl:
                lines.append(f"Benchmark TVL: ${tvl:.1f}B across top 5 bluechip pools.\n")
        
        pools = m.get('defi_bluechip_pools', [])
        if pools:
            lines.append("| Protocol | Pool | Chain | APY | 30D Avg | TVL | Risk |")
            lines.append("|----------|------|-------|-----|---------|-----|------|")
            for p in pools[:10]:
                risk = p.get('risk', 'emerging')
                risk_emoji = '🟢' if risk == 'bluechip' else '🟡' if risk == 'established' else '🔵'
                lines.append(f"| {p['project']} | {p['symbol']} | {p['chain']} | {p['apy']:.1f}% | {p['apy_30d']:.1f}% | ${p['tvl_m']:.0f}M | {risk_emoji} {risk} |")
        
        return "\n".join(lines) if lines else "Data accumulating..."
    
    def _eth_benchmark(self, m: Dict) -> str:
        bench = m.get('eth_benchmark_apy', 0)
        staking = m.get('defi_eth_staking', [])
        
        lines = []
        if bench:
            lines.append(f"**ETH Staking Benchmark: {bench:.2f}% APY**\n")
        
        if staking:
            lines.append("| Protocol | Token | APY | 30D | TVL |")
            lines.append("|----------|-------|-----|-----|-----|")
            for p in staking[:6]:
                lines.append(f"| {p['project']} | {p['symbol']} | {p['apy']:.2f}% | {p['apy_30d']:.2f}% | ${p['tvl_m']:.0f}M |")
        
        return "\n".join(lines) if lines else "Data accumulating..."
    
    def _defi_vs_tradfi(self, m: Dict) -> str:
        usd_bench = m.get('usd_benchmark_apy', 0)
        t3m = m.get('treasury_3m', 0)
        t10y = m.get('treasury_10y', m.get('us10y_current', 0))
        
        lines = []
        lines.append("| Instrument | Yield | Notes |")
        lines.append("|-----------|-------|-------|")
        
        if usd_bench:
            lines.append(f"| 🔵 DeFi USD Benchmark | **{usd_bench:.2f}%** | Top 5 bluechip stablecoin pools |")
        lines.append(f"| 🟢 Cenoa Earn | **5.00%** | No lock-up, instant withdrawal |")
        if t3m:
            lines.append(f"| 🇺🇸 US 3-Month T-Bill | **{t3m:.2f}%** | Risk-free government rate |")
        if t10y:
            lines.append(f"| 🇺🇸 US 10-Year Note | **{t10y:.2f}%** | Long-term benchmark |")
        lines.append(f"| 🏦 US Savings Account | **~0.50%** | Traditional bank deposit |")
        
        if usd_bench and t3m:
            spread = usd_bench - t3m
            if spread > 0:
                lines.append(f"\nDeFi yields are **{spread:.1f}bps above** T-Bills — DeFi offers a premium for smart contract risk.")
            else:
                lines.append(f"\nDeFi yields are **{abs(spread):.1f}bps below** T-Bills — unusual, may indicate capital rotation into DeFi (yield compression).")
        
        return "\n".join(lines)
    
    def _top_opportunities(self, m: Dict) -> str:
        pools = m.get('defi_bluechip_pools', [])
        if not pools:
            return "Data accumulating..."
        
        # Sort by APY for top opportunities
        sorted_pools = sorted(pools, key=lambda x: x['apy'], reverse=True)
        
        lines = ["**Top 5 by APY (Bluechip only):**\n"]
        for i, p in enumerate(sorted_pools[:5], 1):
            risk = p.get('risk', '')
            lines.append(f"{i}. **{p['project']} {p['symbol']}** on {p['chain']} — **{p['apy']:.1f}% APY** (TVL ${p['tvl_m']:.0f}M) [{risk}]")
        
        return "\n".join(lines)
    
    def _capital_flows(self, m: Dict) -> str:
        lines = []
        
        etf_daily = m.get('etf_net_flow_daily', 0)
        etf_7d = m.get('etf_net_flow_7d', 0)
        if etf_7d:
            direction = "inflows" if etf_7d > 0 else "outflows"
            lines.append(f"**BTC ETF:** ${etf_7d/1e6:+,.0f}M weekly {direction}" + (f" (${etf_daily/1e6:+,.0f}M today)" if etf_daily else ""))
        
        fg = m.get('fear_greed_value', 0)
        if fg:
            lines.append(f"**Sentiment:** Fear & Greed at {fg} ({self._fg_label(fg)})")
        
        dom = m.get('btc_dominance', 0)
        if dom:
            lines.append(f"**BTC Dominance:** {dom:.1f}%")
        
        # Protocol TVL summary
        tvls = m.get('defi_protocol_tvls', [])
        if tvls:
            movers = [p for p in tvls if abs(p.get('change_1d', 0)) > 1]
            if movers:
                lines.append("\n**Notable TVL moves (1d):**")
                for p in movers[:3]:
                    lines.append(f"- {p['name']}: ${p['tvl_b']}B ({p['change_1d']:+.1f}%)")
        
        return "\n".join(lines) if lines else "Data accumulating..."
    
    def _em_currencies(self, m: Dict) -> str:
        currencies = {
            'usdtry': ('🇹🇷', 'Turkish Lira', 'TRY'),
            'usdngn': ('🇳🇬', 'Nigerian Naira', 'NGN'),
            'usdpkr': ('🇵🇰', 'Pakistani Rupee', 'PKR'),
            'usdegp': ('🇪🇬', 'Egyptian Pound', 'EGP'),
            'usdbrl': ('🇧🇷', 'Brazilian Real', 'BRL'),
        }
        
        lines = ["| Currency | Rate | 1D Change | Note |",
                 "|----------|------|-----------|------|"]
        
        for key, (flag, name, code) in currencies.items():
            rate = m.get(f'{key}_rate', 0)
            chg = m.get(f'{key}_change_1d', 0)
            if rate:
                note = ""
                if chg > 0.5:
                    note = "USD strengthening — hold USDC"
                elif chg < -0.5:
                    note = "Local currency gaining — good time to convert"
                lines.append(f"| {flag} USD/{code} | {rate:,.2f} | {chg:+.1f}% | {note} |")
        
        return "\n".join(lines) if len(lines) > 2 else "Currency data loading..."
    
    def _what_to_watch(self, m: Dict) -> str:
        lines = []
        
        fomc_hours = m.get('fomc_hours_until')
        if fomc_hours and isinstance(fomc_hours, (int, float)) and 0 < fomc_hours < 168:
            lines.append(f"- **FOMC Meeting** in {fomc_hours:.0f} hours — expect volatility around the announcement")
        
        cpi_hours = m.get('cpi_hours_until')
        if cpi_hours and isinstance(cpi_hours, (int, float)) and 0 < cpi_hours < 168:
            lines.append(f"- **CPI Release** in {cpi_hours:.0f} hours — inflation data moves markets")
        
        fg = m.get('fear_greed_value', 50)
        if fg <= 20:
            lines.append("- **Extreme Fear** persists — watch for potential reversal signals")
        elif fg >= 80:
            lines.append("- **Extreme Greed** — be cautious of potential correction")
        
        usd_bench = m.get('usd_benchmark_apy', 0)
        t3m = m.get('treasury_3m', 0)
        if usd_bench and t3m and usd_bench < t3m:
            lines.append("- **DeFi yields below T-Bills** — unusual condition, watch for rate normalization")
        
        if not lines:
            lines.append("- Markets in regular pattern — no major events on the immediate horizon")
        
        return "\n".join(lines)
    
    def _fg_label(self, v):
        if v <= 25: return 'Extreme Fear'
        if v <= 45: return 'Fear'
        if v <= 55: return 'Neutral'
        if v <= 75: return 'Greed'
        return 'Extreme Greed'
